### ISSUE TITLE
Disconnect at Submission: Vanderbilt ScRNA-seq L1 & L2

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/HTAN-data-curator#38]
**Describe the bug**
Vanderbilt collaborator reports the app disconnects after hitting submit 
(CL confirmed behavior in both staging and production apps) 

**To Reproduce**
1. In DCA: select Vanderbilt, single_cell_RNAseq_level_1 , single cell level 1 template
2. Upload template (attached below)
3. Template validates without error
4. App disconnects at submission

**Expected behavior**
Manifest is submitted to Synapse

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

**Screenshots**

**Desktop (if applicable, please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]
 - Version [Version 103.0.5060.114 (Official Build) (x86_64)]

**Additional context**
Templates: 
[HTAN scRNA-seq Level 1_JS added.csv](https://github.com/ncihtan/HTAN-data-curator/files/9954998/HTAN.scRNA-seq.Level.1_JS.added.csv)
[HTAN scRNA-seq Level 2.csv](https://github.com/ncihtan/HTAN-data-curator/files/9954997/HTAN.scRNA-seq.Level.2.csv)

This was also reported via the Jira Service Desk here: https://sagebionetworks.jira.com/browse/HTAN-135

**Comment by adamjtaylor** [comment]
Thanks for reporting @clarisse-lau 
This does look to possibly be a table issue as it is crashing on something around a table uuid.

FYI @milen-sage and @elv-sb.

Shiny logs:

```
2022-11-07T21:03:50.950295+00:00 shinyapps[5750996]: Starting R with process ID: '390'
2022-11-07T21:03:50.950702+00:00 shinyapps[5750996]: Shiny application starting ...
2022-11-07T21:03:52.794677+00:00 shinyapps[5750996]: Listening on http://127.0.0.1:36753
2022-11-07T21:04:03.545487+00:00 shinyapps[5750996]: Welcome, Adam Taylor!
2022-11-07T21:04:03.545533+00:00 shinyapps[5750996]: INFO: [2022-11-07 21:04:03] synapseclient_default - Welcome, Adam Taylor!
2022-11-07T21:06:51.729182+00:00 shinyapps[5750996]: Warning: Setting row names on a tibble is deprecated.
2022-11-07T21:07:13.085507+00:00 shinyapps[5750996]: Warning: Setting row names on a tibble is deprecated.
2022-11-07T21:07:13.127403+00:00 shinyapps[5750996]: Warning: Error in py_call_impl: ValueError: Cannot set non-string value 'd804a3f4-41cc-472a-a698-68cca618b803' into a StringArray.
2022-11-07T21:07:13.127441+00:00 shinyapps[5750996]: Detailed traceback:
2022-11-07T21:07:13.127445+00:00 shinyapps[5750996]:   File "/srv/connect/apps/HTAN-data-curator-staging/.venv/lib/python3.8/site-packages/schematic/store/synapse.py", line 1052, in associateMetadataWithFiles
2022-11-07T21:07:13.127460+00:00 shinyapps[5750996]:     manifest.loc[idx, 'Uuid'] = gen_uuid
2022-11-07T21:07:13.127464+00:00 shinyapps[5750996]:   File "/srv/connect/apps/HTAN-data-curator-staging/.venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 818, in __setitem__
2022-11-07T21:07:13.127467+00:00 shinyapps[5750996]:     iloc._setitem_with_indexer(indexer, value, self.name)
2022-11-07T21:07:13.127471+00:00 shinyapps[5750996]:   File "/srv/connect/apps/HTAN-data-curator-staging/.venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1795, in _setitem_with_indexer
2022-11-07T21:07:13.127474+00:00 shinyapps[5750996]:     self._setitem_with_indexer_split_path(indexer, value, name)
2022-11-07T21:07:13.127481+00:00 shinyapps[5750996]:   File "/srv/connect/apps/HTAN-data-curator-staging/.venv/lib/python3.8/site-packages/pandas/core/indexing.py", line 1888, in _setitem_with_indexer_split_path
2022-11-07T21:07:13.127489+00:00 shinyapps[5750996]:     self._setitem_single_column(loc, value, pi)
2022-11-07T21:07:13.127492+00:00 shinyapps[5750996]:   File "/srv/connect/apps/HTAN-data-curator-st [... truncated]
2022-11-07T21:07:13.133879+00:00 shinyapps[5750996]:   15: <Anonymous>
2022-11-07T21:07:13.133891+00:00 shinyapps[5750996]:   13: fn
2022-11-07T21:07:13.133894+00:00 shinyapps[5750996]:    8: retry
2022-11-07T21:07:13.133898+00:00 shinyapps[5750996]:    7: connect$retryingStartServer
2022-11-07T21:07:13.133902+00:00 shinyapps[5750996]:    6: eval
2022-11-07T21:07:13.133912+00:00 shinyapps[5750996]:    5: eval
2022-11-07T21:07:13.133917+00:00 shinyapps[5750996]:    4: eval
2022-11-07T21:07:13.133921+00:00 shinyapps[5750996]:    3: eval
2022-11-07T21:07:13.133927+00:00 shinyapps[5750996]:    2: eval.parent
2022-11-07T21:07:13.133931+00:00 shinyapps[5750996]:    1: local
```

**Comment by adamjtaylor** [comment]
Should submit as a FAIR data service desk ticket.

**Comment by aclayton555** [comment]
Issue filed with FAIR: https://sagebionetworks.jira.com/servicedesk/customer/portal/5/IBCSPRT-100

**Comment by GiaJordan** [comment]
Confirming receipt of this issue by FAIR data

**Comment by GiaJordan** [comment]
Addressed in https://github.com/Sage-Bionetworks/schematic/pull/1006
@adamjtaylor @aclayton555 @clarisse-lau

**Comment by aclayton555** [comment]
Thanks @GiaJordan ! Note that HTAN DCC team would like to leave this issue open until we can confirm this issue has been resolved with the contributor. This process helps us close the loop with contributors.
@adamjtaylor or @clarisse-lau are there any additional steps required before we can reach out to our Vanderbilt contributor to confirm whether they are now able to successfully submit?

**Comment by GiaJordan** [comment]
No problem @aclayton555; sorry about the auto closure of the issue! 
This change should be included in the next schematic release

**Comment by aclayton555** [comment]
Thank you!! To close the loop on the FAIR side, I think this ticket can be closed out @milen-sage : https://sagebionetworks.jira.com/servicedesk/customer/portal/5/IBCSPRT-100 
(I know we are still getting familiar with the ticketing/escalation processes, so I hope this makes sense)

**Comment by adamjtaylor** [comment]
schematic v22.11.2 is scheduled for release tomorrow, 2022-11-15. Will redeploy staging to confirm this fixes. Then scheduled to roll up to production at end of current sprint.

**Comment by clarisse-lau** [comment]
Thanks all! Is the fix for this issue now implemented in staging?

**Comment by adamjtaylor** [comment]
Looks like it was released yesterday but after I last rebuilt staging.
Have set off rebuild so should be in staging once this action is complete
https://github.com/ncihtan/HTAN-data-curator/actions/runs/3499115116

**Comment by clarisse-lau** [comment]
Perfect, thank you!

**Comment by clarisse-lau** [comment]
I was able to submit both manifests in staging. 
Thanks again @GiaJordan @adamjtaylor !

**Comment by aclayton555** [comment]
Awesome! Thank you all! @clarisse-lau will you also follow-up with the center. I think you were looped into the initial email thread referenced in this ticket: https://sagebionetworks.jira.com/browse/HTAN-135

**Comment by clarisse-lau** [comment]
Thanks to you as well @aclayton555!

Marisol had actually reached out previously in a smaller thread about the same issue, which I've responded to.

**Comment by GiaJordan** [comment]
You're welcome @clarisse-lau!
